//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cjenovnik
    {
        public int CjenovnikID { get; set; }
        public string Konzola { get; set; }
        public string Vrijeme_od { get; set; }
        public string Vrijeme_do { get; set; }
        public string Cijena { get; set; }
    }
}
