//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class konzola
    {
        public konzola()
        {
            this.manager = new HashSet<manager>();
        }
    
        public int konzolaID { get; set; }
        public string pozicija { get; set; }
        public string naziv { get; set; }
    
        public virtual konzola konzola1 { get; set; }
        public virtual konzola konzola2 { get; set; }
        public virtual ICollection<manager> manager { get; set; }
    }
}
