//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager
    {
        public int managerID { get; set; }
        public int korisnikID { get; set; }
        public System.DateTime datum { get; set; }
        public int konzolaID { get; set; }
        public string pocetnoVrijme { get; set; }
        public string Zavrsetak { get; set; }
        public string Totaltime { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual konzola konzola { get; set; }
        public virtual korisnici korisnici { get; set; }
    }
}
